### ISSUE TITLE
Todo 2017

### ISSUE THREAD

**Issue by benlachman** [nicemohawk/nmf-ios#2]
### Todos for 2017

- [x] Use EJSON: https://github.com/Shopify/ejson
- Clean up map view
  - [x] Move current location button onto map
  - [x] Add Google maps routing (action button)
  - [x] Do we need to update map?
- Schedule tab
  - [ ] Highlight some items?
    - [x] Remove stars from some items (gates open, etc.)
  - [x] Add "no starred items" to timeline
  - [ ] Support alphabetized list of artists when they don't have a time assigned.
    - Ordered after artists on the same day 
    - Ordered after artists with a day
  - [x] _Stretch_: local notifications for starred items
- Info tab
  - [x] update Info
  - [x] Move "buy tickets" to the top of info
